PORT: 80
HOST: 0.0.0.0
SECRET_KEY: null # Change to something secure
SQLALCHEMY_DATABASE_URI: null # Change to your server configuration
PDF_STORAGE_FOLDER: '/home/blacklist/pdfs'
THUMBNAIL_STORAGE_FOLDER: '/home/blacklist/thumbnails'